import { Eye, HeartHandshake, History, LockKeyhole, Map, Paintbrush, ShieldCheck, Sparkles, UsersRound, Zap } from "lucide-react";

const about = [
  { title:"A shared public artifact", icon:<Sparkles/>, text:"The Free Pixel Wall is a collaborative drawing space where thousands of small decisions gradually become one evolving image. Visitors can explore the wall without an account. Registered contributors can claim a compact plot, add pixel art, refine their work over time, and leave a visible record of participation." },
  { title:"A canvas with memory", icon:<History/>, text:"The visible canvas shows the latest state of every pixel, but the wall also keeps a placement history. When artwork changes, the project still remembers who contributed, when they were active, which colors they used, and how the public image evolved. Pixel Replay turns that history into a timeline you can watch." },
  { title:"One plot per person", icon:<Map/>, text:"Every account receives one bounded 32 x 32 plot after publishing its first pixel. This keeps the wall open to many contributors and prevents any single person from taking over the entire surface. You can continue revising your plot, experiment with colors, or erase mistakes inside your own area." },
  { title:"Built for wandering", icon:<Eye/>, text:"The wall is intentionally much larger than one screen. Navigate mode lets you pan across the canvas, zoom toward your cursor, jump to open areas, and inspect coordinate labels. Recent placement cards can take you directly to another contributor's newest work with a precise blue highlight." },
  { title:"Part art wall, part social experiment", icon:<UsersRound/>, text:"There is no payment system, premium tier, or purchasable territory. The interesting part is what happens when people share a limited visual language: a grid, a palette, a small plot, and enough time to create something recognizable. Leaderboards celebrate activity without turning the wall into a marketplace." },
  { title:"Designed to stay approachable", icon:<HeartHandshake/>, text:"The tools are simple on purpose: navigate, draw, erase, choose a color, and pick a brush size. The wall should feel understandable within a minute while still rewarding curiosity. Whether you leave a tiny icon, a pattern, or a carefully composed miniature scene, your mark becomes part of the larger artifact." }
];

const rules = [
  { title:"Use one account and one plot", icon:<Map/>, text:"Each contributor gets one 32 x 32 plot. Do not create duplicate accounts to claim extra territory, bypass plot boundaries, or crowd out other artists. The point is to make something thoughtful with a small amount of space." },
  { title:"Draw with care", icon:<Paintbrush/>, text:"Add original artwork, refine your own plot, or participate in a daily prompt. Avoid flooding the canvas with meaningless noise, repeatedly painting over shared areas just to disrupt them, or using the eraser as a way to spoil other contributions." },
  { title:"Keep the wall welcoming", icon:<UsersRound/>, text:"Do not create hateful, harassing, threatening, sexually explicit, or illegal imagery. Avoid publishing personal information, impersonating other people, or using usernames and artwork to target someone. This is a public wall, so create with a public audience in mind." },
  { title:"Respect the pace", icon:<Zap/>, text:"Cooldowns, rate limits, and new-account brush restrictions exist to keep drawing fair and the live wall responsive. Do not automate placements, run scripts, coordinate flooding attempts, or try to bypass technical limits. Fast participation is welcome; abusive volume is not." },
  { title:"Understand what history means", icon:<History/>, text:"Pixel placement and erase actions are tracked so replay, activity lists, profiles, and leaderboards remain meaningful. Your latest batch can be undone when you make a mistake, but the wall is not an anonymous scratchpad. Contribute only what you are comfortable associating with your public handle." },
  { title:"Protect your account", icon:<LockKeyhole/>, text:"Choose a strong password and keep your login details private. Your email address is used for authentication and is not shown publicly. If you notice unexpected changes to your plot, sign out and stop using the account until its credentials can be updated." },
  { title:"Explore without disrupting", icon:<Eye/>, text:"Anyone can pan, zoom, use recent-placement links, inspect the heatmap, and watch replay mode. Exploration is encouraged. When you switch into Draw or Erase, make sure you are working inside your intended plot and that your changes add something worthwhile." },
  { title:"Help the experiment stay useful", icon:<ShieldCheck/>, text:"The project works best when contributors treat the wall as a shared creative space rather than a competition to dominate pixels. Moderation tools may be added as the community grows. Until then, use good judgment and leave room for the next person." }
];

export function InfoPage({type}:{type:"about"|"rules"}){
  const isAbout=type==="about", data=isAbout?about:rules;
  return <main className="grid-glow min-h-[calc(100vh-64px)] px-5 py-14"><div className="mx-auto max-w-5xl">
    <p className="text-xs font-bold uppercase tracking-[.22em] text-cyan-300">{isAbout?"About the experiment":"Community guide"}</p>
    <h1 className="soft-title mt-3 text-4xl font-black sm:text-5xl">{isAbout?"A canvas with a memory.":"Make your mark thoughtfully."}</h1>
    <p className="mt-5 max-w-3xl text-base leading-7 text-zinc-400">{isAbout?"The Free Pixel Wall is a free collaborative canvas, a public archive of tiny creative choices, and a social experiment about what people make when everyone receives a small corner of a much larger space.":"The wall stays interesting when contributors create with care, respect the technical limits, and remember that other people are sharing the same public space. These guidelines explain the expectations clearly."}</p>
    <div className="mt-10 grid gap-3 sm:grid-cols-2">{data.map(({title,text,icon})=><section key={title} className="glass flex gap-4 rounded-2xl p-5"><span className="mt-1 shrink-0 text-cyan-300">{icon}</span><div><h2 className="font-black">{title}</h2><p className="mt-2 text-sm leading-6 text-zinc-500">{text}</p></div></section>)}</div>
    <div className="mt-8 flex items-center gap-3 rounded-2xl border border-cyan-400/20 bg-cyan-400/5 px-5 py-4 text-sm text-cyan-100">{isAbout?<HeartHandshake/>:<ShieldCheck/>}<b>{isAbout?"Free to use. Designed for shared curiosity.":"Create freely. Share the wall responsibly."}</b></div>
  </div></main>
}
